mod decode;
mod hosting;
mod model;
mod webpublish_capnp; // generated by build.rs

use anyhow::{Context, Result};
use decode::WebPublishStream;
use tokio::task;

#[tokio::main]
async fn main() -> Result<()> {
    let configs = task::spawn_blocking(|| WebPublishStream::from_stdin().collect::<Vec<_>>())
        .await
        .context("web publish reader task failed")?;

    for item in configs {
        let config = item.context("failed to decode web publish message")?;
        config
            .hosting_designation
            .apply(&config)
            .await
            .context("failed to apply hosting designation")?;
        println!(
            "WebPublish: processed configuration for {}",
            config.site_identity.canonical_id
        );
    }
    Ok(())
}
