mod decode;
mod hosting;
mod model;
mod spore_capnp; // generated by build.rs

use anyhow::{Context, Result};
use decode::SporeStream;

fn main() -> Result<()> {
    for item in SporeStream::from_stdin() {
        let config = item.context("failed to decode spore")?;
        config
            .hosting
            .apply(&config)
            .context("failed to apply hosting")?;
        println!("Mycelia Spore: hosting updated for site {}", config.site.id);
    }
    Ok(())
}
